export function generateHTML(graph: string, title = "MIRROR") {

  return `<!doctype html>
<html>
<head>
<meta charset="UTF-8" />
<title>${title}</title>
<script type="module">
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.esm.min.mjs';
  mermaid.initialize({
    startOnLoad: true,
    theme: 'base',
    flowchart: { useMaxWidth: false, htmlLabels: true, curve: 'basis' },
    themeVariables: {
      background: '#020617',
      primaryColor: '#0f172a',
      primaryBorderColor: '#334155',
      primaryTextColor: '#e2e8f0',
      lineColor: '#475569',
      fontFamily: 'Inter',
      fontSize: '14px'
    }
  });
</script>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    min-height: 100vh;
    background: radial-gradient(circle at top left, #1e293b, #020617);
    color: white;
    font-family: Inter, system-ui, sans-serif;
    overflow: hidden;
  }
  .header { padding: 40px 48px 24px; }
  h1 {
    font-size: 72px;
    font-weight: 800;
    letter-spacing: -3px;
    background: linear-gradient(90deg, #60a5fa, #818cf8);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
  }
  .subtitle { margin-top: 10px; color: rgba(255,255,255,0.55); font-size: 18px; }
  .graph-shell { padding: 0 32px 32px; }
  .graph-container {
    height: calc(100vh - 180px);
    overflow: auto;
    border-radius: 24px;
    background: rgba(255,255,255,0.04);
    border: 1px solid rgba(255,255,255,0.08);
    backdrop-filter: blur(20px);
    padding: 32px;
  }
  .mermaid {
    min-width: 1600px;
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 120px;
    font-size: 14px;
  }
  svg { max-width: none !important; }
  .footer { position: fixed; bottom: 16px; right: 24px; color: rgba(255,255,255,0.3); font-size: 12px; }
</style>
</head>
<body>
  <div class="header">
    <h1>${title}</h1>
    <div class="subtitle">Understand repositories instantly.</div>
  </div>
  <div class="graph-shell">
    <div class="graph-container">
      <div class="mermaid">
${graph}
      </div>
    </div>
  </div>
  <div class="footer">Generated by MIRROR</div>
</body>
</html>
`
}
